- name: Docker stop and remove containers
  vars:
    container_names:
      - frontend
    containers: "{{ item }}"
  include_tasks:
    file: roles/common/tasks/docker_stop_remove_tasks.yml
    apply:
      tags:
        - frontend
  loop: "{{ container_names | batch(1) | list }}"
  tags:
    - frontend

- name: Spin up new containers
  docker_compose:
    project_src: "temp/frontend"
    build: yes
    debug: yes
  become: true
  register: started_containers
  tags:
    - frontend