version: "3.5"
services:
    elasticsearch:
        image: amazon/opendistro-for-elasticsearch:1.13.2
        container_name: elasticsearch
        network_mode: host
        environment:
            discovery.type: single-node
            bootstrap.memory_lock: "true"
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            - ../elasticsearch:/elasticsearch
            - ../elasticsearch/config/elasticsearch.yml:/elasticsearch.yml
    redis:
        container_name: redis
        network_mode: host
        build:
            context: ./modules/CuckooFilter
        volumes:
            - ../redis:/redis
        command: redis-server /usr/local/etc/redis/redis.conf
    backend:
        container_name: backend
        network_mode: host
        build:
            context: .
        depends_on:
            - elasticsearch
        volumes:
            - ../backend:/server
        command: gunicorn -w 4 -b 0.0.0.0:3001 app:app
    frontend:
        container_name: frontend
        network_mode: host
        build:
            context: ./frontend
        depends_on:
            - backend
        volumes:
            - ../frontend:/frontend
        command: http-server dist --port 3002