version: "3.5"
services:
    elasticsearch:
        image: elasticsearch:7.12.0
        environment:
            discovery.type: single-node
            bootstrap.memory_lock: "true"
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ../elasticsearch:/elasticsearch
            - ../elasticsearch/config/elasticsearch.yml:/elasticsearch.yml
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - stack-connector
    redis:
        build:
            context: ./modules/CuckooFilter
        volumes:
            - ../redis:/redis
        ports:
            - 6379:6379
        networks:
            - stack-connector
        command: redis-server /usr/local/etc/redis/redis.conf
    backend:
        build:
            context: .
        ports:
            - "3001:3001"
        depends_on:
            - elasticsearch
        volumes:
            - ../backend:/server
        networks:
            - stack-connector
        command: gunicorn -w 4 -b 0.0.0.0:3001 app:app
    frontend:
        build:
            context: ./frontend
        ports:
            - "3002:8080"
        depends_on:
            - backend
        volumes:
            - ../frontend:/frontend
        networks:
            - stack-connector
        command: http-server dist
    
networks:
    stack-connector:
        name: stack-connector
        driver: bridge
        ipam:
            driver: default