- name: Stop and remove container
  vars:
    container_names:
      - opensearch-master
      - opensearch-data-ingest1
      - opensearch-data-ingest2
      - opensearch-data-ingest3
      - opensearch-coordinator
      - opensearch-dashboards
    containers: "{{ item }}"
  include_tasks:
    file: roles/common/tasks/docker_stop_remove_tasks.yml
    apply:
      tags:
        - opensearch
  loop: "{{ container_names | batch(1) | list }}"
  tags:
    - opensearch

- name: Spin up new container
  docker_compose:
    project_src: "temp/compose/opensearch"
    build: true
    debug: true
  become: true
  register: started_containers
  tags:
    - opensearch

- name: Wait for opensearch to start
  command: docker exec opensearch curl localhost:9200/_recovery -sS
  register: result
  until: result.stdout == '{}'
  retries: 30
  delay: 5 # Seconds
  become: true
  tags:
    - opensearch
    - opensearch_base_indexes
    - opensearch_knn_indexes

- name: Create base indexes
  shell:
    cmd: "python3.8 import_data.py"
    chdir: "temp/minitask"
  register: create_base
  tags:
    - opensearch_base_indexes

- debug: var=create_base

- name: Create KNN indexes
  shell:
    cmd: "python3.8 index.py"
    chdir: "temp/knn_indexing"
  register: create_knn
  tags:
    - opensearch_knn_indexes

- debug: var=create_knn
