- name: Stop and remove container
  vars:
    container_names:
      - elasticsearch
    containers: "{{ item }}"
  include_tasks: roles/common/tasks/docker_stop_remove_tasks.yml
  loop: "{{ container_names | batch(1) | list }}"
  tags:
    - elasticsearch

- name: Spin up new container
  docker_compose:
    project_src: "temp/compose/elasticsearch"
    build: yes
    debug: yes
  become: true
  register: started_containers
  tags:
    - elasticsearch

- name: Wait for elasticsearch to start
  command: docker exec elasticsearch curl localhost:9200/_recovery -sS
  register: result
  until: result.stdout == '{}'
  retries: 30
  delay: 5 # Seconds
  become: true
  tags:
    - elasticsearch
    - elasticsearch_base_indexes
    - elasticsearch_knn_indexes

- name: Create base indexes
  shell:
    cmd: "python3 import_data.py"
    chdir: "temp/minitask"
  tags:
    - elasticsearch_base_indexes

- name: Create KNN indexes
  shell:
    cmd: "python3 index.py"
    chdir: "temp/knn_indexing"
  tags:
    - elasticsearch_knn_indexes
