- name: Stop and remove container
  vars:
    container_names:
      - elasticsearch
    containers: "{{ item }}"
  include_tasks:
    file: roles/common/tasks/docker_stop_remove_tasks.yml
    apply:
      tags:
        - elasticsearch
  loop: "{{ container_names | batch(1) | list }}"
  tags:
    - elasticsearch

- name: Spin up new container
  docker_compose:
    project_src: "temp/compose/elasticsearch"
    build: true
    debug: true
  become: true
  register: started_containers
  tags:
    - elasticsearch

- name: Wait for elasticsearch to start
  command: docker exec elasticsearch curl localhost:9200/_recovery -sS
  register: result
  until: result.stdout == '{}'
  retries: 30
  delay: 5 # Seconds
  become: true
  tags:
    - elasticsearch
    - elasticsearch_base_indexes
    - elasticsearch_knn_indexes

- name: Create base indexes
  shell:
    cmd: "python3.8 import_data.py"
    chdir: "temp/minitask"
  register: create_base
  tags:
    - elasticsearch_base_indexes

- debug: var=create_base

- name: Create KNN indexes
  shell:
    cmd: "python3.8 index.py"
    chdir: "temp/knn_indexing"
  register: create_knn
  tags:
    - elasticsearch_knn_indexes

- debug: var=create_knn
