version: "3.5"
services:
  caddy:
    image: caddy/caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../caddy/Caddyfile:/etc/caddy/Caddyfile
