version: "3.5"
services:
  caddy:
    image: caddy/caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../caddy/Caddyfile:/etc/caddy/Caddyfile
      # These start out empty and fill with cache data
      # - caddy/data:/data
      # - caddy/config:/config
