version: "3.5"
services:
    elasticsearch:
        container_name: opensearch
        build:
            context: .
        environment:
            discovery.type: single-node
            plugins.security.disabled: "true" # This will need to be enabled when TLS is fixed
            bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping
            OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
            - 9300:9300 
            