version: "3.5"
services:
    opensearch-master:
        build:
            context: .
        container_name: opensearch-master
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch-master
            - node.master=true
            - node.data=false
            - node.ingest=false
            - discovery.seed_hosts=opensearch-master,opensearch-data-ingest-1,opensearch-data-ingest-2,opensearch-coordinator
            - cluster.initial_master_nodes=opensearch-master
            - plugins.security.disabled=true # NOTE: This will need to be removed when SSL if configured
            - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
            - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
                hard: 65536
        volumes:
            - opensearch-master:/usr/share/opensearch/data
        ports:
            - 9200:9200
            - 9600:9600
        networks:
            - opensearch-net
    opensearch-data-ingest1:
        build:
            context: .
        container_name: opensearch-data-ingest1
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch-data-ingest1
            - node.master=false
            - node.data=true
            - node.ingest=true
            - discovery.seed_hosts=opensearch-master,opensearch-data-ingest-1,opensearch-data-ingest-2,opensearch-coordinator
            - cluster.initial_master_nodes=opensearch-master
            - plugins.security.disabled=true # NOTE: This will need to be removed when SSL if configured
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        networks:
            - opensearch-net
        ports:
            - 9201:9200
            - 9601:9600
        volumes:
            - opensearch-data-ingest1:/usr/share/opensearch/data
    opensearch-data-ingest2:
        build:
            context: .
        container_name: opensearch-data-ingest2
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch-data-ingest2
            - node.master=false
            - node.data=true
            - node.ingest=true
            - discovery.seed_hosts=opensearch-master,opensearch-data-ingest-1,opensearch-data-ingest-2,opensearch-coordinator
            - cluster.initial_master_nodes=opensearch-master
            - plugins.security.disabled=true # NOTE: This will need to be removed when SSL if configured
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        networks:
            - opensearch-net
        ports:
            - 9202:9200
            - 9602:9600
        volumes:
            - opensearch-data-ingest2:/usr/share/opensearch/data
    opensearch-data-ingest3:
        build:
            context: .
        container_name: opensearch-data-ingest3
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch-data-ingest3
            - node.master=false
            - node.data=true
            - node.ingest=true
            - discovery.seed_hosts=opensearch-master,opensearch-data-ingest-1,opensearch-data-ingest-2,opensearch-coordinator
            - cluster.initial_master_nodes=opensearch-master
            - plugins.security.disabled=true # NOTE: This will need to be removed when SSL if configured
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        networks:
            - opensearch-net
        ports:
            - 9203:9200
            - 9603:9600
        volumes:
            - opensearch-data-ingest3:/usr/share/opensearch/data
    opensearch-coordinator:
        build:
            context: .
        container_name: opensearch-coordinator
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch-coordinator
            - node.master=false
            - node.data=false
            - node.ingest=false
            - discovery.seed_hosts=opensearch-master,opensearch-data-ingest-1,opensearch-data-ingest-2,opensearch-coordinator
            - cluster.initial_master_nodes=opensearch-master
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        networks:
            - opensearch-net
        ports:
            - 9204:9200
            - 9604:9600
        volumes:
            - opensearch-coordinator:/usr/share/opensearch/data
    opensearch-dashboards:
        image: opensearchproject/opensearch-dashboards:latest
        container_name: opensearch-dashboards
        networks:
            - opensearch-net
        ports:
            - 5601:5601
        volumes:
            - ./opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml


volumes:
    opensearch-master:
    opensearch-data-ingest1:
    opensearch-data-ingest2:
    opensearch-data-ingest3:
    opensearch-coordinator:

networks:
    opensearch-net:
