name: Ansible Deployment

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY_FILE: id_rsa
      ANSIBLE_DIR: .
      PLAYBOOK: playbooks/deploy.yml
    steps:
      - uses: actions/checkout@v2
      - name: Install ansible
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo apt-add-repository -yu ppa:ansible/ansible
          sudo apt install -y ansible
          ansible-galaxy collection install community.general
      - name: Create key file
        run: |
          echo "$SSH_PRIVATE_KEY" > $PRIVATE_KEY_FILE
          sudo chmod 0600 $PRIVATE_KEY_FILE
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      - name: Verify targets are accessible
        run: ansible all --private-key=$PRIVATE_KEY_FILE -m ping
        # working-directory: ansible
      - name: Run playbook
        run: ansible-playbook -v --private-key=$PRIVATE_KEY_FILE --extra-vars "ansible_sudo_pass=${{ secrets.SUDO_PASS }}" $PLAYBOOK
        # working-directory: ansible
      - name: Remove key file
        run: sudo rm -rf $PRIVATE_KEY_FILE
