name: Ansible Deployment

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEYS_DIR: keys
      PRIVATE_KEY_FILE: id_rsa
      ANSIBLE_DIR: ansible
      PLAYBOOK: playbooks/deploy.yml
    steps:
      - uses: actions/checkout@v2
      - name: Install ansible
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo apt-add-repository -yu ppa:ansible/ansible
          sudo apt install -y ansible
          sudo ansible-galaxy collection install community.general
      - name: Create key file
        run: |
          mkdir -p $KEYS_DIR
          echo "$SSH_PRIVATE_KEY" > $KEYS_DIR/$PRIVATE_KEY_FILE
          sudo chmod 0600 $KEYS_DIR/$PRIVATE_KEY_FILE
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      - name: Verify targets are accessible
        run: sudo ansible all --private-key=$KEYS_DIR/$PRIVATE_KEY_FILE -m ping
        working-directory: $ANSIBLE_DIR
      - name: Run playbook
        run: sudo ansible-playbook -v --private-key=$KEYS_DIR/$PRIVATE_KEY_FILE --extra-vars "ansible_sudo_pass=${{ secrets.SUDO_PASS }}" $PLAYBOOK
        working-directory: $ANSIBLE_DIR
      - name: Remove key file
        run: sudo rm -rf $KEYS_DIR